name: check

on:
  pull_request:
  push:
    branches:
      - 'master'

jobs:
  build:
    name: Run checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with Gradle
        run: ./gradlew check